### ISSUE TITLE
Metaprogramming in ruby

### ISSUE THREAD

**Issue by ngprnk** [RubyNepal/rorh#15]
This topic would help new comers to understand how rails dynamic helpers works? How other rails magic works underneath.

**Comment by zoras** [comment]
Hi @ngprnk, this topic has already been covered in our previous meetup.

See pics here: http://www.meetup.com/Nepal-Ruby-Users-Group/photos/26406995/441971834/#441971834

You can grab the slides and code examples from here: http://files.meetup.com/18762323/MetaProgramming%20in%20Ruby%20-%20Ruby%20Nepal%20Meetup%20-%20Sep%2013%2C%202015.zip

I'm closing this presentation request; let me know if you meant otherwise.
